### PR TITLE
Admin module testing

### PR DESCRIPTION
**Pull request by bandstrar**
--Fixed order history to show the newest orders at the top
--Fixed dog and cat stores to not display pajamas that are inactive
--Fixed past order totals to only show 2 decimal places
--Fixed add/update pajama to allow IsActive and Pattern to be set to false
--Fixed add/update pajama to not allow user to set Price below 0.01 and inventory below 0

### CODE REVIEW

**Review by danapham — CHANGES_REQUESTED** [review]
- orders are not displaying based on order date
- update is now not letting me set price to anything that doesn't have .01 at the end

**Comment by bandstrar** [comment]
> * orders are not displaying based on order date
> * update is now not letting me set price to anything that doesn't have .01 at the end

Both should be fixed now

**Review by danapham — APPROVED** [review]
nice job!

**Review by wppattonjr — APPROVED** [review]
Looks good 👍🏿

**Pull request merged**
